export const projectsData = {
  "1": {
    title: "Modern Architecture",
    category: "Architecture Photography",
    year: "2024",
    role: "Lead Photographer",
    tools: ["Canon EOS R5", "Adobe Lightroom", "Photoshop"],
    description:
      "A comprehensive architectural photography project showcasing modern design principles and innovative building techniques. This project explores the intersection of form and function in contemporary architecture.",
    challenge:
      "Capturing the essence of modern architecture while highlighting the interplay of light, shadow, and structural elements.",
    solution:
      "Utilized advanced photography techniques and post-processing to create compelling visual narratives that emphasize the building's unique characteristics.",
    images: [
      "/modern-architecture-building.png",
      "/modern-architecture-exterior.png",
      "/modern-architecture-interior.png",
    ],
    websiteUrl: "#",
  },
  "2": {
    title: "Brand Identity Design",
    category: "Branding & Design",
    year: "2024",
    role: "Creative Director",
    tools: ["Adobe Illustrator", "Figma", "After Effects"],
    description:
      "Complete brand identity system including logo design, color palette, typography, and brand guidelines for a modern tech startup.",
    challenge: "Creating a distinctive brand identity that stands out in a crowded tech market.",
    solution:
      "Developed a bold, colorful visual language that communicates innovation and creativity while maintaining professional credibility.",
    images: ["/brand-identity-design-colorful.jpg", "/brand-guidelines-concept.png", "/logo-design-collection.jpg"],
    websiteUrl: "#",
  },
  "3": {
    title: "Mobile App Interface",
    category: "UI/UX Design",
    year: "2024",
    role: "UI/UX Designer",
    tools: ["Figma", "Principle", "Adobe XD"],
    description:
      "Modern mobile application interface design focusing on user experience and intuitive navigation patterns.",
    challenge: "Creating an intuitive interface that works seamlessly across different device sizes.",
    solution: "Implemented a flexible design system with responsive components and clear visual hierarchy.",
    images: ["/mobile-app-interface.png", "/web-dashboard-analytics.png", "/brand-guidelines-concept.png"],
    websiteUrl: "#",
  },
  "4": {
    title: "Editorial Fashion Photography",
    category: "Fashion Photography",
    year: "2024",
    role: "Fashion Photographer",
    tools: ["Sony A7R IV", "Capture One", "Photoshop"],
    description: "High-end editorial fashion photography showcasing contemporary fashion trends and styling.",
    challenge: "Capturing the essence of fashion while maintaining artistic integrity.",
    solution: "Collaborated with stylists and models to create compelling visual narratives.",
    images: ["/editorial-fashion-photography.jpg", "/professional-portrait.png", "/creative-workspace.png"],
    websiteUrl: "#",
  },
  "5": {
    title: "Web Dashboard Analytics",
    category: "Web Design",
    year: "2024",
    role: "Product Designer",
    tools: ["Figma", "React", "D3.js"],
    description: "Comprehensive analytics dashboard design with data visualization and real-time monitoring.",
    challenge: "Presenting complex data in an accessible and visually appealing way.",
    solution: "Created an intuitive dashboard with interactive charts and clear data hierarchy.",
    images: ["/web-dashboard-analytics.png", "/mobile-app-interface.png", "/brand-identity-design-colorful.jpg"],
    websiteUrl: "#",
  },
  "6": {
    title: "Product Packaging Design",
    category: "Packaging Design",
    year: "2024",
    role: "Packaging Designer",
    tools: ["Adobe Illustrator", "Dimension", "Photoshop"],
    description: "Innovative product packaging design that combines functionality with aesthetic appeal.",
    challenge: "Creating packaging that stands out on shelves while being eco-friendly.",
    solution: "Developed sustainable packaging with bold graphics and practical design.",
    images: ["/product-packaging-design.png", "/brand-identity-design-colorful.jpg", "/logo-design-collection.jpg"],
    websiteUrl: "#",
  },
  "7": {
    title: "Interior Design Visualization",
    category: "3D Visualization",
    year: "2024",
    role: "3D Artist",
    tools: ["Blender", "V-Ray", "Photoshop"],
    description: "Photorealistic interior design visualization for residential and commercial spaces.",
    challenge: "Creating realistic renders that accurately represent materials and lighting.",
    solution: "Utilized advanced rendering techniques and material libraries for photorealism.",
    images: ["/modern-living-room.png", "/modern-architecture-interior.png", "/creative-workspace.png"],
    websiteUrl: "#",
  },
  "8": {
    title: "Logo Design Collection",
    category: "Logo Design",
    year: "2024",
    role: "Brand Designer",
    tools: ["Adobe Illustrator", "Figma"],
    description: "Collection of logo designs for various clients across different industries.",
    challenge: "Creating unique, memorable logos that represent each brand's identity.",
    solution: "Developed versatile logo systems that work across all media and applications.",
    images: ["/logo-design-collection.jpg", "/brand-identity-design-colorful.jpg", "/brand-guidelines-concept.png"],
    websiteUrl: "#",
  },
}
